name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install Tools
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y wget build-essential python3 python3-pip \
            verilator libevent-dev libjson-c-dev device-tree-compiler \
            python3-setuptools python3-requests python3-pexpect \
            python3-colorama python3-serial python3-packaging python3-yaml \
            ninja-build
          pip3 install meson

      # Install (n)Migen / LiteX / Cores
      - name: Install LiteX
        run: |
          wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
          python3 litex_setup.py init install --user

      # Install RISC-V GCC
      - name: Install RISC-V GCC
        run: |
          wget https://static.dev.sifive.com/dev-tools/freedom-tools/v2020.12/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
          tar -xf $PWD/riscv64-*.tar.gz
          sudo mkdir /usr/local/riscv
          sudo cp -r $PWD/riscv64-*/* /usr/local/riscv

      # Test
      - name: Run Tests
        run: |
          export PATH=/usr/local/riscv/bin:$HOME/.local/bin:$PATH
          python3 -m unittest test.test_build
